"""init

Revision ID: 4833010823e2
Revises:
Create Date: 2025-12-15 04:26:11.004433

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4833010823e2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "boards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boards_id"), "boards", ["id"], unique=False)
    op.create_index(op.f("ix_boards_owner_id"), "boards", ["owner_id"], unique=False)
    op.create_index(op.f("ix_boards_title"), "boards", ["title"], unique=False)
    op.create_table(
        "columns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "board_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_column_position",
        ),
    )
    op.create_index(op.f("ix_columns_board_id"), "columns", ["board_id"], unique=False)
    op.create_index(op.f("ix_columns_id"), "columns", ["id"], unique=False)
    op.create_index(op.f("ix_columns_position"), "columns", ["position"], unique=False)
    op.create_index(op.f("ix_columns_title"), "columns", ["title"], unique=False)
    op.create_table(
        "invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + make_interval(secs=>86400.0)"),
            nullable=False,
        ),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invites_board_id"), "invites", ["board_id"], unique=False)
    op.create_index(op.f("ix_invites_id"), "invites", ["id"], unique=False)
    op.create_index(
        op.f("ix_invites_invited_by"), "invites", ["invited_by"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_board_id"), "tags", ["board_id"], unique=False)
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.create_index(op.f("ix_tags_title"), "tags", ["title"], unique=True)
    op.create_table(
        "user_board_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("board_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("custom_title", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "manager", "admin", name="role"), nullable=False
        ),
        sa.Column(
            "custom_permissions",
            sa.ARRAY(
                sa.Enum(
                    "BOARD_VIEW",
                    "BOARD_WRITE",
                    "BOARD_MANAGE",
                    "BOARD_INVITE_LINK",
                    "CARD_MOVE",
                    "CARD_UPDATE_STATUS",
                    "USER_MANAGE",
                    name="permission",
                )
            ),
            nullable=False,
        ),
        sa.Column("notification_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "board_id", name="uq_board_pref"),
        sa.UniqueConstraint("user_id", "position", name="uq_board_position"),
    )
    op.create_index(
        op.f("ix_user_board_preferences_board_id"),
        "user_board_preferences",
        ["board_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_board_preferences_id"),
        "user_board_preferences",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_board_preferences_position"),
        "user_board_preferences",
        ["position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_board_preferences_user_id"),
        "user_board_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["column_id"], ["columns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "column_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_card_position",
        ),
    )
    op.create_index(
        op.f("ix_cards_assigned_to"), "cards", ["assigned_to"], unique=False
    )
    op.create_index(op.f("ix_cards_column_id"), "cards", ["column_id"], unique=False)
    op.create_index(op.f("ix_cards_id"), "cards", ["id"], unique=False)
    op.create_index(op.f("ix_cards_position"), "cards", ["position"], unique=False)
    op.create_index(op.f("ix_cards_title"), "cards", ["title"], unique=False)
    op.create_table(
        "card_tag_associations",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("card_id", "tag_id"),
        sa.UniqueConstraint("tag_id", "card_id", name="uq_tags_for_card"),
    )
    op.create_table(
        "checklists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checklists_author_id"), "checklists", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_checklists_card_id"), "checklists", ["card_id"], unique=False
    )
    op.create_index(op.f("ix_checklists_id"), "checklists", ["id"], unique=False)
    op.create_index(op.f("ix_checklists_title"), "checklists", ["title"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_comments_card_id"), "comments", ["card_id"], unique=False)
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=False)
    op.create_index(op.f("ix_comments_text"), "comments", ["text"], unique=False)
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("checklist_id", sa.UUID(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checklist_id"], ["checklists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checklist_items_checklist_id"),
        "checklist_items",
        ["checklist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checklist_items_id"), "checklist_items", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checklist_items_id"), table_name="checklist_items")
    op.drop_index(op.f("ix_checklist_items_checklist_id"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_index(op.f("ix_comments_text"), table_name="comments")
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_card_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_checklists_title"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_id"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_card_id"), table_name="checklists")
    op.drop_index(op.f("ix_checklists_author_id"), table_name="checklists")
    op.drop_table("checklists")
    op.drop_table("card_tag_associations")
    op.drop_index(op.f("ix_cards_title"), table_name="cards")
    op.drop_index(op.f("ix_cards_position"), table_name="cards")
    op.drop_index(op.f("ix_cards_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_column_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_assigned_to"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(
        op.f("ix_user_board_preferences_user_id"), table_name="user_board_preferences"
    )
    op.drop_index(
        op.f("ix_user_board_preferences_position"), table_name="user_board_preferences"
    )
    op.drop_index(
        op.f("ix_user_board_preferences_id"), table_name="user_board_preferences"
    )
    op.drop_index(
        op.f("ix_user_board_preferences_board_id"), table_name="user_board_preferences"
    )
    op.drop_table("user_board_preferences")
    op.drop_index(op.f("ix_tags_title"), table_name="tags")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_board_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_invites_invited_by"), table_name="invites")
    op.drop_index(op.f("ix_invites_id"), table_name="invites")
    op.drop_index(op.f("ix_invites_board_id"), table_name="invites")
    op.drop_table("invites")
    op.drop_index(op.f("ix_columns_title"), table_name="columns")
    op.drop_index(op.f("ix_columns_position"), table_name="columns")
    op.drop_index(op.f("ix_columns_id"), table_name="columns")
    op.drop_index(op.f("ix_columns_board_id"), table_name="columns")
    op.drop_table("columns")
    op.drop_index(op.f("ix_boards_title"), table_name="boards")
    op.drop_index(op.f("ix_boards_owner_id"), table_name="boards")
    op.drop_index(op.f("ix_boards_id"), table_name="boards")
    op.drop_table("boards")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
